### ISSUE TITLE
Get account address from ID

### ISSUE THREAD

**Issue by ig-shaun** [ixofoundation/ixo-assistant#2]
Users of ixo blockchains get a decentralised identifier (DID) which is linked to their account address.

The DID is in the standard format did:ixo:fje8934hdY78b...
Account address is in the format ixo3Jjia9rohx...

To get an address from a given DID, we use  https://testnet.ixo.world/didToAddr/<did>
(Replace testnet.ixo.world with the correct path for the main-net or other ixo networks),

For testing, use the following network node endpoint and DID:
https://impacthub.ixo.world/didToAddr/did:sov:CYCc2xaJKrp8Yt947Nc6jd

Which should return
```json
{
  "height": "0",
  "result": "ixo19h3lqj50uhzdrv8mkafnp55nqmz4ghc2sd3m48"
}
```

**Comment by ChikkaUdayaSai** [comment]
@ig-shaun , Can you provide me the working ENDPOINT url and some test DID and their corresponding Addresses?
